import matplotlib.pyplot as plt
import pandas as pd
import os


def ensure_output_dir():
    """Create the output directory for plots if it doesn't exist."""
    if not os.path.exists('output_plots'):
        os.makedirs('output_plots')


def plot_revenue_by_salesperson(df):
    """Bar chart: Total revenue generated by each salesperson."""
    ensure_output_dir()
    revenue = df.groupby('Salesperson')['Total_Revenue'].sum().sort_values(ascending=True)

    fig, ax = plt.subplots(figsize=(10, 6))
    revenue.plot(kind='barh', color='steelblue', ax=ax)
    ax.set_title('Total Revenue by Salesperson', fontsize=14, fontweight='bold')
    ax.set_xlabel('Revenue ($)', fontsize=12)
    ax.set_ylabel('Salesperson', fontsize=12)
    ax.grid(axis='x', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig('output_plots/revenue_by_salesperson.png', dpi=300)
    plt.close()
    print("Saved: output_plots/revenue_by_salesperson.png")


def plot_sales_by_region(df):
    """Pie chart: Proportion of sales contributed by each region."""
    ensure_output_dir()
    revenue = df.groupby('Region')['Total_Revenue'].sum()

    fig, ax = plt.subplots(figsize=(8, 8))
    colors = ['#ff9999', '#66b3ff', '#99ff99', '#ffcc99']
    wedges, texts, autotexts = ax.pie(
        revenue,
        labels=revenue.index,
        autopct='%1.1f%%',
        startangle=140,
        colors=colors,
        textprops={'fontsize': 12}
    )
    ax.set_title('Sales Share by Region', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig('output_plots/sales_by_region.png', dpi=300)
    plt.close()
    print("Saved: output_plots/sales_by_region.png")


def plot_monthly_trend(df):
    """Line chart: Revenue trend over months."""
    ensure_output_dir()
    df['Month'] = df['Date'].dt.to_period('M')
    monthly = df.groupby('Month')['Total_Revenue'].sum()

    fig, ax = plt.subplots(figsize=(12, 6))
    monthly.plot(kind='line', marker='o', color='darkgreen', linewidth=2, ax=ax)
    ax.set_title('Monthly Revenue Trend', fontsize=14, fontweight='bold')
    ax.set_xlabel('Month', fontsize=12)
    ax.set_ylabel('Revenue ($)', fontsize=12)
    ax.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig('output_plots/monthly_trend.png', dpi=300)
    plt.close()
    print("Saved: output_plots/monthly_trend.png")


def plot_transaction_distribution(df):
    """Histogram: Distribution of individual transaction amounts."""
    ensure_output_dir()
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.hist(df['Total_Revenue'], bins=40, color='mediumpurple', edgecolor='black', alpha=0.8)
    ax.set_title('Distribution of Transaction Amounts', fontsize=14, fontweight='bold')
    ax.set_xlabel('Transaction Amount ($)', fontsize=12)
    ax.set_ylabel('Frequency', fontsize=12)
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig('output_plots/transaction_distribution.png', dpi=300)
    plt.close()
    print("Saved: output_plots/transaction_distribution.png")


def generate_all_plots(filepath='sales_data.csv'):
    """Load data and generate all visualizations."""
    df = pd.read_csv(filepath)
    df['Date'] = pd.to_datetime(df['Date'])
    df['Total_Revenue'] = df['Units_Sold'] * df['Unit_Price']

    plot_revenue_by_salesperson(df)
    plot_sales_by_region(df)
    plot_monthly_trend(df)
    plot_transaction_distribution(df)
    print("\nAll visualizations generated successfully!")


if __name__ == "__main__":
    generate_all_plots()

